# Generated by Django 4.2.3 on 2023-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_courierprofile_customerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CU", "Customer"),
                    ("CO", "Courier"),
                    ("RM", "Restaurant Manager"),
                    ("MO", "Moderator"),
                ],
                max_length=2,
            ),
        ),
    ]
