# Generated by Django 4.2.3 on 2024-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image_url",
            field=models.URLField(
                default="https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D"
            ),
            preserve_default=False,
        ),
    ]
