# Generated by Django 4.2.3 on 2024-05-08 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
        migrations.DeleteModel(
            name="CourierProfile",
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
    ]
