version: '3.6'
name: 'user'

services:
    db:
        image: postgres:15.4-alpine
        container_name: postgres
        ports:
          - "5433:5432"
        volumes:
          - ~/apps/postgres:/var/lib/postgresql/data
        environment:
          - PGPORT=5433
          - POSTGRES_USER=${PG_USER}
          - POSTGRES_PASSWORD=${PG_PASSWORD}
          - POSTGRES_DB=user
        expose:
          - "5433"
    app:
        build:
          context: ../
          dockerfile: ./docker/app/Dockerfile
        container_name: app
        ports:
          - "8000:8000"
          - "50051:50051"
        environment:
          - SECRET_KEY=${SECRET_KEY}
          - DJANGO_CONFIGURATION=Develop
          - WEB_APP_PROTOCOL=http
          - WEB_APP_HOST=0.0.0.0
          - WEB_APP_PORT=8000
          - GRPC_SERVER_PORT=50051
          - PG_HOST=db
          - PG_PORT=5433
          - PG_DATABASE=user
          - PG_USER=${PG_USER}
          - PG_PASSWORD=${PG_PASSWORD}
          - EMAIL_HOST=smtp.yandex.ru
          - EMAIL_HOST_USER=${EMAIL_HOST_USER}
          - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
          - EMAIL_PORT=465
          - EMAIL_USE_SSL=True
        depends_on:
          - db
