"""manager

Revision ID: 2d08c0a225b7
Revises: f375a62daf6d
Create Date: 2023-08-17 00:13:05.324094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d08c0a225b7'
down_revision: Union[str, None] = 'f375a62daf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_managers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.add_column('menu_categories', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu_categories', 'restaurants', ['restaurant_id'], ['id'], use_alter=True)
    op.add_column('menu_items', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'menus', 'restaurants', ['restaurant_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'restaurants', 'menus', ['current_menu_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'restaurant_id')
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    op.drop_column('menu_categories', 'restaurant_id')
    op.drop_table('restaurant_managers')
    # ### end Alembic commands ###
