"""image_url

Revision ID: 42091e5fdc4c
Revises: 62ae7f320470
Create Date: 2024-05-11 16:49:13.658184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42091e5fdc4c'
down_revision: Union[str, None] = '62ae7f320470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_categories', 'image_url')
    # ### end Alembic commands ###
