"""initial

Revision ID: 4a98536c54c4
Revises: 
Create Date: 2023-09-07 11:39:34.981766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a98536c54c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('current_menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_menu_id'], ['menus.id'], name='fk_current_menu_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_menu_id')
    )
    op.create_table('menu_items',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_managers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('menu_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name='fk_menu_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_items_association',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name='fk_category_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], name='fk_item_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_items_association')
    op.drop_table('menu_categories')
    op.drop_table('restaurant_managers')
    op.drop_table('menus')
    op.drop_table('menu_items')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
