"""menu_item_image_url

Revision ID: 62ae7f320470
Revises: 070d78e53dbb
Create Date: 2024-02-19 18:18:37.741190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ae7f320470'
down_revision: Union[str, None] = '070d78e53dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image_url')
    # ### end Alembic commands ###
