"""removed_restaurant_id

Revision ID: 8c4ce1a9eeec
Revises: bf607583185f
Create Date: 2023-09-05 10:45:07.665197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4ce1a9eeec'
down_revision: Union[str, None] = 'bf607583185f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_categories_restaurant_id_fkey', 'menu_categories', type_='foreignkey')
    op.drop_column('menu_categories', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('menu_categories_restaurant_id_fkey', 'menu_categories', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
