"""rating

Revision ID: b62ede61cb1f
Revises: 42091e5fdc4c
Create Date: 2024-06-13 20:01:32.833615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62ede61cb1f'
down_revision: Union[str, None] = '42091e5fdc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('reviews_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'reviews_count')
    op.drop_column('menu_items', 'rating')
    # ### end Alembic commands ###
