"""menu_id

Revision ID: bf607583185f
Revises: 8c4058b3d642
Create Date: 2023-09-04 20:12:45.190118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf607583185f'
down_revision: Union[str, None] = '8c4058b3d642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_categories_association')
    op.add_column('menu_categories', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu_categories', 'menus', ['menu_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    op.drop_column('menu_categories', 'menu_id')
    op.create_table('menu_categories_association',
    sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name='menu_categories_association_category_id_fkey'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name='menu_categories_association_menu_id_fkey'),
    sa.PrimaryKeyConstraint('menu_id', 'category_id', name='menu_categories_association_pkey')
    )
    # ### end Alembic commands ###
