"""restaurant_id

Revision ID: ffb0202db3d6
Revises: 2d08c0a225b7
Create Date: 2023-08-18 23:51:50.708659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb0202db3d6'
down_revision: Union[str, None] = '2d08c0a225b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'restaurant_managers', 'restaurants', ['restaurant_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_managers', type_='foreignkey')
    # ### end Alembic commands ###
