version: '3.6'
name: 'menu'

services:
    db:
        image: postgres:15.4-alpine
        container_name: menu-postgres
        ports:
          - "5433:5432"
        volumes:
          - ~/apps/postgres/menu:/var/lib/postgresql/data
        environment:
          - PGPORT=5433
          - POSTGRES_USER=${PG_USER}
          - POSTGRES_PASSWORD=${PG_PASSWORD}
          - POSTGRES_DB=menu
        expose:
          - "5433"
        networks:
          - menu_network
    app:
        build:
          context: ../
          dockerfile: ./docker/app/Dockerfile
        container_name: menu-app
        ports:
          - "8001:8001"
        environment:
          - CONFIGURATION=Develop
          - WEB_APP_HOST=0.0.0.0
          - WEB_APP_PORT=8001
          - ROLES_GRPC_SERVER_HOST=user-app
          - ROLES_GRPC_SERVER_PORT=50051
          - PG_HOST=db
          - PG_PORT=5433
          - PG_DATABASE=menu
          - PG_USER=${PG_USER}
          - PG_PASSWORD=${PG_PASSWORD}
          - KAFKA_BOOTSTRAP_SERVER_HOST=kafka
          - KAFKA_BOOTSTRAP_SERVER_PORT=9092
          - KAFKA_BROKER_USER=${KAFKA_BROKER_USER}
          - KAFKA_BROKER_PASSWORD=${KAFKA_BROKER_PASSWORD}
          - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
        depends_on:
          - db
        networks:
          - menu_network
          - user_grpc_network
          - kafka_kafka_network

networks:
  user_grpc_network:
    external: true
  kafka_kafka_network:
    external: true
  menu_network:
