"""restaurant_application

Revision ID: 4837d8afea9e
Revises: 02934b0803ac
Create Date: 2023-10-12 11:39:57.988469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4837d8afea9e'
down_revision: Union[str, None] = '02934b0803ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_applications',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('application_type', sa.Enum('create', 'update', name='applicationtype'), nullable=False),
    sa.Column('restaurant_manager_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_manager_id'], ['restaurant_managers.id'], name='fk_restaurant_manager_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_manager_id')
    )
    op.alter_column('moderators', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('restaurant_managers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('restaurant_managers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_managers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurant_managers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('moderators', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('restaurant_applications')
    op.execute("DROP TYPE applicationtype")
    # ### end Alembic commands ###
