"""rating

Revision ID: 83339bfb4ba9
Revises: 14d857f469c9
Create Date: 2024-06-14 00:15:58.602016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83339bfb4ba9'
down_revision: Union[str, None] = '14d857f469c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('rating', sa.Float(decimal_return_scale=2), nullable=True))
    op.add_column('restaurants', sa.Column('reviews_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'reviews_count')
    op.drop_column('restaurants', 'rating')
    # ### end Alembic commands ###
