"""type

Revision ID: 9bc3dc886db6
Revises: 4837d8afea9e
Create Date: 2023-10-19 14:36:48.681912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bc3dc886db6'
down_revision: Union[str, None] = '4837d8afea9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_applications', sa.Column('type', sa.Enum('create', 'update', name='applicationtype'), nullable=False))
    op.drop_column('restaurant_applications', 'application_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_applications', sa.Column('application_type', postgresql.ENUM('create', 'update', name='applicationtype'), autoincrement=False, nullable=False))
    op.drop_column('restaurant_applications', 'type')
    # ### end Alembic commands ###
